add_newline = true

format = """
[*✹⊹](mauve) $shell$time$directory$git_branch$git_status$git_commit$git_state$git_metrics$aws
$character
"""

[aws.region_aliases]
ap-northeast-1 = "jp"

[directory]
truncation_length = 100
truncate_to_repo = false

[package]
disabled = true

[time]
disabled = false

[shell]
disabled = false

[git_metrics]
disabled = false
